baseURL: "/"
languageCode: "fr-fr" 
title: "People Story"

module:
  imports:
    - path: github.com/theNewDynamic/gohugo-theme-ananke

DefaultContentLanguage: fr
SectionPagesMenu: main
Paginate: 3
googleAnalytics: ''
enableRobotsTXT: true
sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml
params:
  favicon: ''
  site_logo: ''
  description: Communication Digitale spécialisé en Vidéo
  facebook: ''
  twitter: 
  instagram: ''
  youtube: ''
  github: ''
  gitlab: ''
  linkedin: ''
  mastodon: ''
  slack: ''
  stackoverflow: ''
  rss: ''
  body_classes: "baskerville"
  site_logo: "images/4201f8_3498a615dcb0436c803a6716aaff73a8~mv2.png"
  background_color_class: bg-black
  featured_image: /images/gohugo-default-sample-hero-image.jpg
  recent_posts_number: 2
